services:
  jupyter_notebook:
    container_name: jupyter_notebook
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks:cached
      - ./credentials:/workspace/credentials:cached
    env_file:
      - .env
